### ISSUE TITLE
Map with responses displays blank screen instead

### ISSUE THREAD

**Issue by Kenji-K** [kobotoolbox/kpi#2670] opened 2020-05-13 03:31 UTC
## Description

I installed kobo with kobo-install just to test the system on my workstation. I created a dummy form and attempted to see the map containing the responses but I just got a blank screen.

## Steps to Reproduce

1. Just installed with [kobo-install](https://github.com/kobotoolbox/kobo-install)
2. Created a form with two questions, one of a georeferenced point.
3. Clicked the map report of the form.

## Expected behavior 

The responses displayed on a map.

## Actual behavior 

Just a blank screen, console displays the following error:

```
vendors-52e7a4ce58527d62940e.js:247 TypeError: Cannot read property '0' of undefined
    at map.es6:250
    at Array.forEach (<anonymous>)
    at t.value (map.es6:249)
    at t.value (map.es6:133)
    at Al (vendors-52e7a4ce58527d62940e.js:247)
    at t.unstable_runWithPriority (vendors-52e7a4ce58527d62940e.js:255)
    at Gi (vendors-52e7a4ce58527d62940e.js:247)
    at Ol (vendors-52e7a4ce58527d62940e.js:247)
    at wl (vendors-52e7a4ce58527d62940e.js:247)
    at vendors-52e7a4ce58527d62940e.js:247
```

## Additional details

I'm running on docker with WSL2 on Windows. A colleague tried it on Ubuntu. None worked.

**Comment by jnm** [comment] 2020-05-21 03:28
Hi @magicznyleszek, I was trying to test #2533 and saw this. The map appears to be completely broken on kf.master.kbtdev.org in at least the following scenarios:
1. A form has no geographic questions (see #2682, which is probably a duplicate of this, but I included the Sentry link and failing line of code)
1. A form has an optional geographic question, and while the form has responses, the geographic question was never answered (I think this is what #2173 covers)
1. A form has an optional geographic question, and some of the received submissions include responses to the geographic question
1. A form has a geographic question and all submissions include responses to it

I think this has to block our release on production servers.

**Closed** 2020-05-21 22:37 UTC
Labels: CRITICAL, UI & UX, bug
