### ISSUE TITLE
Cascading selects break after renaming questions

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#942] opened 2016-09-28 04:43 UTC
1. Use [sample spreadsheet](https://docs.google.com/spreadsheets/d/1C_uDOkjjbv5Kx3lyOY7ORwM-muW6BKVzdaPMB1X8-2A/edit#gid=0) to create cascading select;
2. Preview the form and observe Enketo open it successfully;
3. Rename one of the questions in the cascading select;
4. Attempt to preview the form;
5. Notice "no survey element with this name" error
   ![screenshot - 09282016 - 12 40 20 am](https://cloud.githubusercontent.com/assets/2085013/18900944/6dfc3926-8514-11e6-9a45-006b74edef78.png)

**Comment by joshuaberetta** [comment] 2021-07-23 19:31
Duplicate of https://github.com/kobotoolbox/kpi/issues/706

**Closed by joshuaberetta** 2021-07-23 19:31 UTC
Labels: bug
