### ISSUE TITLE
Table view: Allow displaying with all label languages

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1623] opened 2018-03-12 17:08 UTC
As a user I'd like to be able to pick which label language to display the HTML table in. Currently one language is picked from a multi label language form while the others are not available to the user.

**Comment by pmusaraj** [comment] 2018-03-14 02:22
Duplicate of #1477. Closing.

**Closed by pmusaraj** 2018-03-14 02:22 UTC

**Comment by pmusaraj** [comment] 2018-04-05 19:16
Fixed in #1665.
