### ISSUE TITLE
Missing columns in exports/table for some projects.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kpi#1056] opened 2016-12-05 16:42 UTC
I.e. Rebecca's project.

**Comment by dorey** [comment] 2017-01-27 20:06
Is this a duplicate of #882 ?

Are there specific columns in a dataset to reference for this? Can it be replicated with a new form?

**Comment by esmail** [comment] 2017-01-30 18:46
An example is the `deppevaluation_philippines` form `aSHhJhLkw575FRZtZqmtJh`. Unsure about which columns.

Possibly the same root issue as #882, but that refers to reports.

**Comment by jnm** [comment] 2018-01-03 22:50
Fixed by https://github.com/kobotoolbox/kpi/pull/1461

**Closed by jnm** 2018-01-03 22:50 UTC
Labels: bug, next-up, reports
