### ISSUE TITLE
Form preview fails inside formbuilder 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1972] opened 2018-08-29 03:53 UTC
## Description
I'm unable to preview (survey snapshot) a form I created a few weeks ago inside the formbuilder. Regular previews in kpi (outside formbuilder) work. 

## Steps to Reproduce

1. Login as nh_er
2. Open [this form](https://kobo.humanitarianresponse.info/#/forms/aZTU7jtmKCMu5siCk485Ga)
3. Click preview

## Expected behavior 

Form previews or error is shown for why preview isn't possible in EE.

## Actual behavior 

![image](https://user-images.githubusercontent.com/673511/44764372-61eb1e00-ab1d-11e8-9531-056c5244607d.png)

## Additional details

I expect it could have to do with the appearances used in the form, though that wouldn't explain why regular previews and the deployed form work.

**Comment by magicznyleszek** [comment] 2018-08-29 07:59
Interesting thing: even after deleting all questions, clearing Layout & Settings tab, and adding single text question - I still get the 500 error when trying to preview

**Comment by joshuaberetta** [comment] 2021-09-07 21:30
No longer breaking/unable to reproduce. I'll close this for now and we can reopen if it shows its head again 👌

**Closed by joshuaberetta** 2021-09-07 21:30 UTC
Labels: bug, formbuilder
