### ISSUE TITLE
Literacy widget not recording data in the database

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2921] opened 2020-12-10 09:27 UTC
## Description

There is no issue with the `literacy widget` while uploading and deploying. However, when collecting data for the `literacy widget` the selected choices does not get stored in the database.

## Steps to Reproduce

1. Upload the literacy widget.
[literacy widget sample.xlsx](https://github.com/kobotoolbox/kpi/files/5671581/literacy.widget.sample.xlsx)
2. Deploy and start collecting data.
![Image 1](https://user-images.githubusercontent.com/50188479/101752222-5d35b280-3af9-11eb-957c-04375cfda58b.png)
3. Submit the collection. It's OK till here.
4. Now check the data that has been submitted to the server. The dataset is empty i.e. there are no recording at all.
![Image 2](https://user-images.githubusercontent.com/50188479/101752298-750d3680-3af9-11eb-88a4-4d53c2f90fa2.png)
Even if you download the dataset you will see nothing.
![Image 3](https://user-images.githubusercontent.com/50188479/101752340-822a2580-3af9-11eb-89f6-1729ca1424e7.png)

## Expected behavior 

The information that is selected should be stored in the dataset. In addition, vital information such as `Duration of exercise`, `Total words attempted` should also be captured. But these information too seems to be blank in the dataset.

## Actual behavior 

Nothing gets stored in the database.

## Additional details

**Link to the community forum discussion:** https://community.kobotoolbox.org/t/literacy-widget-word-at-flash/14362

**Comment by jnm** [comment] 2020-12-11 06:24
Hi @Kalyan-Lama,

I can't reproduce this problem on kf.kobotoolbox.org using Firefox 83.0 on Linux. I uploaded the the attached `literacy widget sample.xlsx` form, made one submission, and exported as XLS. The result was this:

Literacy Question Label!/Word at flash | Literacy Question Label!/Duration of exercise | Literacy Question Label!/Total words attempted | Literacy Question Label! | Literacy Question Label!/Hello! | Literacy Question Label!/How | Literacy Question Label!/are | Literacy Question Label!/you | Literacy Question Label!/today? | Literacy Question Label!/We | Literacy Question Label!/would | Literacy Question Label!/like | Literacy Question Label!/for | Literacy Question Label!/you | Literacy Question Label!/to | Literacy Question Label!/read | Literacy Question Label!/these | Literacy Question Label!/words, | Literacy Question Label!/please. | _id | _uuid | _submission_time | _validation_status | _index
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
13 | 17 | 15 | Hello! are today? would for to read | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 1 | 0 | 0 | 0 | 78145507 | 2f926d7f-3268-450a-8f7e-3771072816e5 | 2020-12-11T06:13:31 |   | 1

It's normal for the table view not to break the response apart into separate columns; there is special logic in the exports for this. However, what you saw is not normal **unless** you didn't mark any of the words. Here's an example of marking several words ~~incorrect~~, a word at flash (blue), and the last word attempted (red):
![image](https://user-images.githubusercontent.com/2085013/101870280-4b7efa00-3b4f-11eb-90a5-620ea0c026a2.png)

If you did mark any words like this and still saw blank data, then please let me know so that I can fix it ASAP.

The user on the forum seems to have reported a different issue:
> The problem is that at the 60 second flash (body::kb:flash), there should be check boxes under the words so the data entrant can identify the last word read. Those boxes were appearing in previous uses, but are missing now. If you run the form and let it go until 60 seconds, the screen flashes yellow, but only one check box appears, under the last word of the passage. They should appear under each word.

I will try now to reproduce that problem.

**Comment by jnm** [comment] 2020-12-11 07:02
I've reproduced the issue described on the forum: https://community.kobotoolbox.org/t/literacy-widget-word-at-flash/14362/9?u=jnm
I'll close this issue in favor of https://github.com/kobotoolbox/enketo-literacy-test-widget/issues/36.
However, please re-open it if you continue to see missing data after marking some words as incorrect etc.

**Comment by Kalyan-Lama** [comment] 2020-12-11 12:59
@jnm,

I tried this in `HHI` server, `Windows 10` OS both with `Chrome` as well as `Firefox` browsers but still could not get it working as it should. I followed the steps outlined below:

* Uploaded the `literacy widget`.
* Deployed the survey project and started to collect data with `Enketo`.
* Strikeout the words and then pressed `Finish` as shown in the image below:
![Image 1](https://user-images.githubusercontent.com/50188479/101905556-bbd55c00-3bdf-11eb-8709-d9d145de977d.png)
* Submitted them to the server.
* Downloaded the data from the server:
![Image 2](https://user-images.githubusercontent.com/50188479/101905766-09ea5f80-3be0-11eb-97ca-3a351cb660e3.png)
* Opened the xls dataset but could see nothing recorded in the dataset:
![Image 3](https://user-images.githubusercontent.com/50188479/101905874-37cfa400-3be0-11eb-9f20-3584cd7af108.png)

**Note:** My `Firefox version is 83.0` while my `Chrome version is 87.0.4280.88`.

Is it because of the OS you are using (`Linux` vs. `Windows`)? But also please be informed that I tried this out in `Ubuntu` but could not succeed.

**Comment by jnm** [comment] 2021-02-19 08:03
@Kalyan-Lama, I know this is old, but for reference, there's one more step after clicking Finish: you have to click a check box to mark the last word that the reader attempted.

In your case, there happens to be only one option. The only word with a check box is the last one, "please", because you had already marked that word has having been read incorrectly (signified by ~~strikethrough~~). In order for it to be incorrect, it would've had to have been attempted, so the widget "knows" that the reader got that far.
![image](https://user-images.githubusercontent.com/2085013/108475435-aecb8d80-725e-11eb-92f5-8c349c59e87c.png)

If you had ticked the box, the widget _should_ have sent the data :sweat_smile: Feel free to re-test and re-open as needed :+1:

**Closed by jnm** 2021-02-19 08:03 UTC
Labels: bug
