### ISSUE TITLE
Bounced back to data page when attempting to edit a record

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1023] opened 2016-11-04 20:19 UTC
To reproduce, go to Data —> Table —> Open (for a specific form) —> Edit, you get bounced back to the Data page. 

User example: 
https://kobo.humanitarianresponse.info/forms/#/forms/ayjvYJgXLahtmxE9nHqS3d/data/table

**Comment by pmusaraj** [comment] 2016-11-09 17:08
@emilykferguson I cannot reproduce this on another form in OCHA, or in our staging or production.

**Comment by pmusaraj** [comment] 2016-11-09 20:13
Ok, so I think the main issue here is that Enketo isn't responding for this form (and I don't know why). 

By the way, I can reproduce the issue locally by going to a specific submission locally and then turning off Enketo. 

I added a potential fix for the redirect here: https://github.com/kobotoolbox/kobocat/pull/295 (on error, redirect back to Data page, not to user dashboard). 

@jnm I am having difficulties testing this outside my local environment, please test.

**Comment by pmusaraj** [comment] 2017-01-24 15:55
Closing, cannot reproduce anymore.

**Closed by pmusaraj** 2017-01-24 15:55 UTC
Labels: bug
