### ISSUE TITLE
reject invalid imports of xlsforms

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1070] opened 2016-12-19 17:22 UTC
* when `asset_type` == `"survey"`

This will prevent users from having broken forms in their list of forms.

Note: Related to support request on OCHA asset `aPswANZHeDXGbCMQUPaAik`

**Comment by magicznyleszek** [comment] 2019-10-19 09:38
Duplicate of https://github.com/kobotoolbox/kpi/issues/1129

**Closed by magicznyleszek** 2019-10-19 09:38 UTC
