### ISSUE TITLE
User is able to import invalid XLS form

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1129] opened 2017-02-01 03:34 UTC
When a user imports an invalid XLS form, the import succeeds but the invalid form is stored, leading to errors when trying to deploy or preview the form. 

See test file: [KOBO TEST.xlsx](https://github.com/kobotoolbox/kpi/files/743804/KOBO.TEST.xlsx)

Preview shows error:
![image](https://cloud.githubusercontent.com/assets/673511/22494405/3fdc3754-e805-11e6-8a88-ee126c38128a.png)

Deployment shows error:
![image](https://cloud.githubusercontent.com/assets/673511/22494398/3979ce44-e805-11e6-8ecb-7c14ddca90ff.png)

Expected behavior: Invalid form is rejected (import fails), and user sees pyxform validation error on the screen to correct the issue.

**Comment by dorey** [comment] 2017-02-01 03:46
I believe the KPI end of the problem is [here](https://github.com/kobotoolbox/kpi/blob/master/kpi/utils/standardize_content.py#L36-L42).

But, `expand_content(...)` and `replace_aliases(...)` are the formpack functions that would probably be the correct place to find the error and catch invalid forms.

**Comment by jnm** [comment] 2019-04-08 05:44
Isn't this a duplicate of https://github.com/kobotoolbox/kpi/issues/1070?

**Comment by tinok** [comment] 2019-04-09 19:27
@jnm Yes, this is a duplicate. But #1070 doesn't have a nice test form :) We should close one of them.

Just retested. The error message is still the same:
![image](https://user-images.githubusercontent.com/673511/55829148-fe29ca00-5adb-11e9-9a48-28b811f5c4d0.png)

**Comment by JacquelineMorrissette** [comment] 2023-08-23 00:33
Closed, the test form is rejected as an upload, as expected

**Closed by JacquelineMorrissette** 2023-08-23 00:33 UTC
Labels: bug
