### ISSUE TITLE
kc-kpi migration script duplicates deployments, formID

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#661] opened 2016-04-25 23:22 UTC
A form deployed only in KC where there is no field called `form_id` in the form receives duplicate deployments and formID in the title. 

[blank] - issue occurs
id_string = xxxx - issue occurs
form_id = xxxx - issue does not occur

[Test XLS forms](https://github.com/kobotoolbox/kpi/files/235579/kpi_bug_661.zip)

![image](https://cloud.githubusercontent.com/assets/673511/14801789/f594be6e-0b00-11e6-9274-c3cbf51ad309.png)

**Comment by jnm** [comment] 2016-05-10 06:54
In my testing, "form_id = xxxx" also causes the issue to occur. The root of the problem is actually in KC, and all the user needs to do is look at the KC projects list to cause the next sync to create duplicates in KPI.

1. The `sync_kobocat_xforms` management command in KPI depends on KC providing a meaningful `date_modified` for each XForm;
1. [XForm has a `num_of_submissions` field that serves as a cache of the Instance count](https://github.com/kobotoolbox/kobocat/blob/7c1a718b2ed3331aa373706c2d190d0498ba65ca/onadata/apps/logger/models/xform.py#L93);
1. [XForm has a `submission_count()` method that calls `save()` on the object whenever `num_of_submissions` is zero](https://github.com/kobotoolbox/kobocat/blob/7c1a718b2ed3331aa373706c2d190d0498ba65ca/onadata/apps/logger/models/xform.py#L203);
1. [The `date_modified` field has `auto_now=True`, causing it to be set to the current time whenever `save()` is called](https://github.com/kobotoolbox/kobocat/blob/7c1a718b2ed3331aa373706c2d190d0498ba65ca/onadata/apps/logger/models/xform.py#L80);
1. [The template code calls the `submission_count()` method whenever the user looks at their project list](https://github.com/kobotoolbox/kobocat-template/blob/e6e9875546e5e5666415856d4f2e34ad5e1d4bfe/templates/published_forms__list.html#L20);
1. The resulting change to `date_modified` causes KPI's `sync_kobocat_xforms` to treat the KC form as a new deployment.

A separate problem with naming, from the dupe (#658), remains a KPI-only bug:
> The form title also isn't as expected (it should be test123 (test123) as per the regular form title (formid)), see screenshot.

**Comment by jnm** [comment] 2016-05-11 19:19
Not going to change KC's `date_modified` behavior, but will rely on the `hash` field instead. KPI solution will require that KC PR https://github.com/kobotoolbox/kobocat/pull/210 be merged.

**Closed** 2016-05-12 14:31 UTC
Labels: bug, in progress
