### ISSUE TITLE
Uploading collections to library fails

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2784] opened 2020-09-03 13:26 UTC
## Description

Importing a Collection from an XLS file is not possible at the moment. It fails because the 'library' sheet is not recognized/allowed. 

## Steps to Reproduce

1. Upload this collection [collection_small.xlsx](https://github.com/kobotoolbox/kpi/files/5168787/collection_small.xlsx)

## Expected behavior 

Collection imports

## Actual behavior 

Error is shown, import fails in API

![image](https://user-images.githubusercontent.com/673511/92120778-7aa30400-edc7-11ea-9c59-8e6b8b5749cb.png)

```
{status: "error", uid: "iNjZFfcf7sYAM5NvkdkJem",…}
date_created: "2020-09-03T13:25:40.323385Z"
messages: {error: "xls upload must have one of these sheets: survey, library", error_type: "SyntaxError"}
error: "xls upload must have one of these sheets: survey, library"
error_type: "SyntaxError"
status: "error"
uid: "iNjZFfcf7sYAM5NvkdkJem"
```

**Comment by jnm** [comment] 2020-09-03 15:32
https://github.com/kobotoolbox/kpi/blob/0feb08adf15d4f748964a9299b898fc9a7c4eb6d/kpi/models/import_export_task.py#L326-L327

**Comment by jnm** [comment] 2020-09-03 16:15
Duplicate of #2262 
![hahahahah](https://user-images.githubusercontent.com/2085013/92140393-07a58780-eddf-11ea-8394-c3e830e85077.gif)

**Closed by jnm** 2020-09-03 16:15 UTC
Labels: bug, high priority
