### ISSUE TITLE
After signing in, user is not redirected to original URL

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3222] opened 2021-05-17 21:57 UTC
## Description

We have an existing option to open React app route upon login. This no longer works on `master` and `beta`.

## Steps to Reproduce

1. Open a form `/#/forms/<uid>/summary`
2. Copy current form url
3. Log out
4. Load form url in browser
5. Observe you ended up on `/accounts/login/?next=/#/forms/<uid>/summary`
6. Log in
7. Observe you ended up on `/#/forms`, not `/#/forms/<uid>/summary`

## Additional details

Good to fix for upcoming #1659

**Comment by jnm** [comment] 2021-05-17 22:47
This was kind of unsolvable with the old way of having the back end redirect to the login page. The server just never sees anything after the `#`. In the new way (#3212), we can have the front end handle redirection to the login page, and the front end then can encode `#` as `%23` when passing it into the `?next=` query parameter.

Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Login.20next.20broken

Example of this (from private repo, but it'll be public soon): https://github.com/kobotoolbox/reports/pull/138/files#diff-73c6079de0524db1d3789cedd5a724aae246d3a77750beec8ce0ba4640465c2dR477-R495

**Comment by jnm** [comment] 2021-05-17 22:50
Actually a duplicate of #2190

**Closed** 2021-06-12 20:06 UTC
Labels: bug
