### ISSUE TITLE
Enketo Formating issues - Legacy Vs KPI

### ISSUE THREAD

**Issue by maskoamas** [kobotoolbox/kpi#1113] opened 2017-01-30 11:23 UTC
Hi Team,

If i upload  an XLS form to Legacy and the same to KPI (new) version the formatting of the text on Enketo appears different.

See screenshot attached
![capture13](https://cloud.githubusercontent.com/assets/9807096/22421330/d465beb0-e6e6-11e6-98a9-348e4549f56c.PNG)

**Comment by tinok** [comment] 2017-02-02 16:40
I recommend renaming this issue to "Formbuilder strips inline formatting from question labels". @dorey

**Comment by pmusaraj** [comment] 2018-01-30 16:14
Duplicate of #1346

**Closed by pmusaraj** 2018-01-30 16:14 UTC
