### ISSUE TITLE
Implement data sub-screens

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#716] opened 2016-05-20 16:19 UTC
Until the different views (map, download, table, and report) are built natively in KPI show an iframe with these pages from kobocat. 

This will require creating a modified view of each screen that can be easily embedded (ie no header elements).

**Comment by tinok** [comment] 2016-06-24 18:18
Small fixes necessary: 

- [ ] Table should take up entire height of the iframe, with page numbers always showing at the bottom
- [ ] `form-view__header form-view__header--named` is a different height depending on whether user is in Forms or Data view
- [ ] After making any changes in the kc iframe settings screen, the page refreshes and [shows the KC project dashboard](https://cloud.githubusercontent.com/assets/673511/16346654/75e0706a-3a16-11e6-92b2-fe7ae475a4e8.png)
 instead of the settings box

**Comment by pmusaraj** [comment] 2016-06-27 12:26
I can't reproduce the third item locally...

**Comment by pmusaraj** [comment] 2016-06-28 01:53
Third item now fixed in KC: https://github.com/kobotoolbox/kobocat/pull/241

**Closed** 2016-07-27 15:00 UTC
Labels: ocha-new-ui
