### ISSUE TITLE
Add support for Enketo PDFs

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1675] opened 2018-03-22 00:59 UTC
https://apidocs.enketo.org/v2#/post-survey-view-pdf
https://www.flowdock.com/app/kobotoolbox/enketo/threads/tncEQLS2ZB1Pk8iqoGbOVCm6nYV

**Comment by tinok** [comment] 2018-03-22 14:29
Closing as duplicate of #1676

**Closed by tinok** 2018-03-22 14:29 UTC
Labels: enhancement
