### ISSUE TITLE
Inserting an & into the form_title breaks Enketo

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kpi#1761] opened 2018-05-03 11:17 UTC
In general using **&** in the `form_title` is not a problem. However, if a **&** character is inserted into the title in the formbuilder, it will not be escaped properly and the form will not load correctly in Enketo. The error messages are something like
`{code: 500, message: "xmlParseEntityRef: no name"}`
or
`{code: 500, message: "EntityRef: expecting ';'"}`
depending on whether there is a character following the **&**.

It doesn't matter whether the form_title is changed using the form edit view in the formbuilder or the *Project title* input:

![image](https://user-images.githubusercontent.com/121946/39573605-309435c6-4ed4-11e8-898d-1670877b687c.png)

When a XLSForm is uploaded that contains a **&** character in the `form_title` cell it works just fine.

**Comment by pmusaraj** [comment] 2018-05-03 12:41
Thanks for the issue. Will look into this shortly.

**Comment by pmusaraj** [comment] 2018-05-03 13:42
I can't reproduce this. I edited the form in both the Form builder and the Project title input, added an &, and the Enketo preview works fine in both cases, with no error. 

Tested with EE 1.52 and EE 1.64.0.

**Comment by jeverling** [comment] 2018-05-03 15:48
The preview actually works fine. But if you take an already deployed form (with **&** or not) and then add an **&** to the title, then re-deploy, you will notice that Enketo doesn't show the changed form / new title and you can see the error in the developer console for Enketo.

This is such a form, re-deployed after adding an **&**: https://ee.kobotoolbox.org/x/#SYZj9TtR

**Comment by jnm** [comment] 2018-05-06 21:46
I was surprised that the Python `requests` library would need this, so I dug into it a little more. I can reproduce this problem in KoBoCAT alone, without using KPI at all; despite `formList` having proper escaping:
```xml
    <xform>
        <formID>amnBrX4y6pbKjjNHsdVBye</formID>
        <name>more &amp; more</name>
        <majorMinorVersion></majorMinorVersion>
        <version></version>
        <hash>md5:df025d33e21f56add304d0896b139ea6</hash>
        <descriptionText>gdmf desc</descriptionText>
        <downloadUrl>http://172.17.0.1:8001/straw/forms/66/form.xml</downloadUrl>
        <manifestUrl>http://172.17.0.1:8001/straw/xformsManifest/66</manifestUrl>
    </xform>
```
...the XML for the form itself is invalid:
```xml
<?xml version="1.0" encoding="utf-8"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>more & more</h:title>
    <model>
      <instance>
[snip]
```

**Comment by jnm** [comment] 2018-05-07 02:43
This needs to be fixed in KoBoCAT:
https://github.com/kobotoolbox/kobocat/blob/9709dbdc64e0ee82f4acb964e2bf1542cdf64878/onadata/apps/logger/models/xform.py#L150-L151

**Comment by jnm** [comment] 2018-05-07 02:48
Apparently Ona just prohibits `&`, `<` and `>` instead of escaping them? 🤔
https://github.com/onaio/onadata/blob/db2987e16d902e038c7af3a1bb895b75d2dd59b0/onadata/apps/logger/models/xform.py#L780-L783

**Comment by jnm** [comment] 2018-05-07 04:29
I opened [an issue](https://github.com/kobotoolbox/kobocat/issues/439) and made a PR on KC to fix this: https://github.com/kobotoolbox/kobocat/pull/440.
@pmusaraj, I assigned you as the reviewer, but feel free to kick it over to @noliveleger.

**Closed by jnm** 2018-05-07 04:29 UTC

**Comment by pmusaraj** [comment] 2018-05-07 13:46
Sure, I'll review it.
