### ISSUE TITLE
Mandatory fields when cloning a form

### ISSUE THREAD

**Issue by maskoamas** [kobotoolbox/kpi#1098] opened 2017-01-20 17:33 UTC
When a form is cloned , the new form resets all fields including the ones not marked as mandatory as 'mandatory'

**Comment by pmusaraj** [comment] 2017-01-24 21:29
I cannot reproduce this issue locally or on kf.kobotoolbox.org. I did the following: 

* created a new form, with three questions, two of which I specifically set as not mandatory (unchecked Mandatory under the question settings)
* deployed the form, opened it in Enketo, and it correctly shows 2 of 3 questions as not mandatory 
* cloned the form, deployed it, and opened the cloned form, and it also has 2 of 3 questions as not mandatory

**Comment by maskoamas** [comment] 2017-01-26 09:34
@pmusaraj  The error is on the OCHA server https://kobo.humanitarianresponse.info/ - A deployed project cloned resets the fields to mandatory . In addition deleted projects re-appear - i have re-deleted them several times last week and they are still somehow repopulated on the list. See attached. The projects marked in yellow are live so **do not delete those** the rest you can delete and simulate if you like.
![capture11](https://cloud.githubusercontent.com/assets/9807096/22326404/d5c37860-e3b2-11e6-916c-146f1ddee7bb.PNG)

**Comment by jnm** [comment] 2017-01-26 14:54
@maskoamas, I can't reproduce this on OCHA with my own account or `fts`. I will send you a screencast on Flowdock, and you can tell us what we're doing differently.

The issue with deleting projects is separate and tracked at https://github.com/kobotoolbox/kpi/issues/1085. The fix for that has already been written and will be included in the next deployment.

**Comment by maskoamas** [comment] 2017-01-27 14:23
@jnm i just tried to reproduce the bug , seems to have dissappeared now. So we are all good on this.

**Closed** 2017-01-27 17:18 UTC
Labels: bug, ready
